schema_version = 2
seed = 0
device = "cpu"

[data]
path = "../../data/adult"

[experiment]
path = "../../exp/adult_smoke/run_001"

[encoding]
num_encoder = "minmax"
cat_encoder = "alb"
seed = 0
histogram_epsilon = 0.1
histogram_delta = 1e-05

[model]
is_y_cond = true
num_classes = 2

[model.rtdl_params]
d_layers = [
    32,
    32,
]
dropout = 0.0
activation = "SiLU"

[diffusion]
num_timesteps = 20
gaussian_loss_type = "mse"
scheduler = "cosine"

[train]
seed = 0
num_workers = 2
epochs = 1
lr = 0.0024384255846226824
weight_decay = 0.0
batch_size = 256

[sample]
seed = 4
class_distribution = "empirical"
num_samples = 512
batch_size = 256

[evaluation]
model = "all"
mode = "synthetic"
seed = 0
catboost_params_path = "catboost.json"

[privacy]
is_dp = false
epsilon = 1.0
max_grad_norm = 1.0
delta = 1e-05
