data_path = "data/default"
exp_path = "exp/default"
device = "cuda:0"
seed = 0

[model_params]
d_in = 44
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    1024,
    1024,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 500
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
epochs = 25
lr = 0.0007286257561853825
weight_decay = 0.0
batch_size = 128

[sample]
num_samples = 18000
batch_size = 256
seed = 4

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[dp]
is_dp = true
epsilon = 10
sigma = 0.58624267578125
max_grad_norm = 1.0
delta = 1e-05
noise_multiplicity_K = 3
